name: net_split
description: "NetSplit - Smart Internet Cost Sharing"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.5.3
  google_fonts: ^8.1.0
  window_manager: ^0.5.1
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  windows:
    generate: true
    image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
